/*CONFIG*/
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

/*SECUENCIAS*/
CREATE SEQUENCE IDX_AREA_SEQ START WITH 1;
CREATE SEQUENCE IDX_ROL_SEQ START WITH 1;
CREATE SEQUENCE IDX_TRAMITE_SEQ START WITH 1;
CREATE SEQUENCE IDX_REGISTRO_ENTRADA_SEQ START WITH 1;
CREATE SEQUENCE IDX_REGISTRO_TRAMITE_SEQ START WITH 1;



/*TABLAS*/
CREATE TABLE ROLES(
    ID_ROL NUMBER DEFAULT IDX_ROL_SEQ.NEXTVAL NOT NULL,
    NOMBRE_ROL VARCHAR2(45),
    PRIMARY KEY (NOMBRE_ROL)
);

CREATE TABLE USUARIOS(
    CEDULA VARCHAR(45) NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR2(45) NOT NULL,
    APELLIDO_1 VARCHAR2(45) NOT NULL,
    APELLIDO_2 VARCHAR2(45) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    PRIMARY KEY (CEDULA)
);

CREATE TABLE USUARIOS_ROLES(
    NOMBRE_ROL VARCHAR(45),
    CEDULA_USUARIO VARCHAR(45) ,
    PRIMARY KEY (NOMBRE_ROL, CEDULA_USUARIO),
    FOREIGN KEY (NOMBRE_ROL) REFERENCES ROLES(NOMBRE_ROL) ON DELETE CASCADE,
    FOREIGN KEY (CEDULA_USUARIO) REFERENCES USUARIOS(CEDULA) ON DELETE CASCADE
);


CREATE TABLE CLIENTES(
    CEDULA VARCHAR2(45) NOT NULL,
    NOMBRE VARCHAR2(45) NOT NULL,
    APELLIDO_1 VARCHAR2(45) NOT NULL,
    APELLIDO_2 VARCHAR2(45) NOT NULL,
    TIPO VARCHAR2(45) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    GENERO VARCHAR2(45) NOT NULL,
    PRIMARY KEY (CEDULA)
);

CREATE TABLE CLIENTES_INVITADOS(
    CEDULA VARCHAR2(45) NOT NULL,
    NOMBRE VARCHAR2(45) NOT NULL,
    APELLIDO_1 VARCHAR2(45) NOT NULL,
    APELLIDO_2 VARCHAR2(45) DEFAULT '',
    TIPO VARCHAR2(45) DEFAULT 'Invitado',
    PRIMARY KEY (CEDULA)
);

CREATE TABLE AREAS(
    ID_AREA NUMBER DEFAULT IDX_AREA_SEQ.NEXTVAL NOT NULL,
    NOMBRE_AREA VARCHAR2(100) NOT NULL,
    DESCRIPCION_AREA VARCHAR2(200) DEFAULT 'N/A',
    FECHA DATE NOT NULL,
    PRIMARY KEY (ID_AREA)
);

CREATE TABLE TRAMITES(
    ID_TRAMITE NUMBER DEFAULT IDX_TRAMITE_SEQ.NEXTVAL NOT NULL,
    NOMBRE_TRAMITE VARCHAR2(100) NOT NULL,
    DESCRIPCION_TRAMITE VARCHAR2(200) DEFAULT 'N/A',
    FECHA DATE NOT NULL,
    ESTADO NUMBER DEFAULT 1,
    PRIMARY KEY (ID_TRAMITE)
);

CREATE TABLE TRAMITES_AREAS(
    ID_AREA NUMBER,
    ID_TRAMITE NUMBER,
    PRIMARY KEY (ID_AREA, ID_TRAMITE),
    FOREIGN KEY (ID_AREA) REFERENCES AREAS(ID_AREA) ON DELETE CASCADE,
    FOREIGN KEY (ID_TRAMITE) REFERENCES TRAMITES(ID_TRAMITE) ON DELETE CASCADE
);

CREATE TABLE REGISTRO_ENTRADA(
    ID_REGISTRO_ENTRADA NUMBER DEFAULT IDX_REGISTRO_ENTRADA_SEQ.NEXTVAL NOT NULL,
    CEDULA_CLIENTE VARCHAR2(45) NOT NULL,
    ID_AREA_DESTINO NUMBER,
    MOTIVO_VISITA VARCHAR2(150),
    FECHA_Y_HORA DATE,
    PRIMARY KEY (ID_REGISTRO_ENTRADA),
    FOREIGN KEY (ID_AREA_DESTINO) REFERENCES AREAS(ID_AREA)
);

CREATE TABLE REGISTRO_TRAMITE(
    ID_REGISTRO_TRAMITE NUMBER DEFAULT IDX_REGISTRO_TRAMITE_SEQ.NEXTVAL NOT NULL,
    CEDULA_CLIENTE VARCHAR2(45) NOT NULL,
    ID_TRAMITE NUMBER,
    DESCRIPCION VARCHAR2(150),
    FECHA_Y_HORA DATE,
    CEDULA_USUARIO VARCHAR2(45) NOT NULL,
    ID_AREA NUMBER NOT NULL,
    PRIMARY KEY (ID_REGISTRO_TRAMITE),
    FOREIGN KEY (ID_TRAMITE) REFERENCES TRAMITES(ID_TRAMITE),
    FOREIGN KEY (ID_AREA) REFERENCES AREAS(ID_AREA)
);

COMMIT;

/*VISTAS*/

CREATE VIEW INFORMACION_CLIENTES AS
SELECT CEDULA, NOMBRE, APELLIDO_1, APELLIDO_2, TIPO 
FROM CLIENTES UNION SELECT * FROM CLIENTES_INVITADOS;

CREATE VIEW AREAS_POR_USUARIO AS
SELECT a.ID_AREA, a.NOMBRE_AREA, ur.CEDULA_USUARIO
FROM USUARIOS_ROLES ur
JOIN ROLES r ON ur.NOMBRE_ROL = r.NOMBRE_ROL
JOIN AREAS a ON r.NOMBRE_ROL = a.NOMBRE_AREA;

CREATE VIEW REPORTE_COMPLETO AS 
SELECT 
    rt.ID_REGISTRO_TRAMITE, 
    a.NOMBRE_AREA, 
    t.NOMBRE_TRAMITE, 
    c.NOMBRE || ' ' || c.APELLIDO_1 || ' ' || c.APELLIDO_2 AS NOMBRE_CLIENTE, 
    u.NOMBRE || ' ' || u.APELLIDO_1 || ' ' || u.APELLIDO_2 AS NOMBRE_USUARIO, 
    rt.FECHA_Y_HORA 
FROM 
    REGISTRO_TRAMITE rt 
    JOIN AREAS a ON rt.ID_AREA = a.ID_AREA 
    JOIN TRAMITES t ON rt.ID_TRAMITE = t.ID_TRAMITE 
    JOIN INFORMACION_CLIENTES c ON rt.CEDULA_CLIENTE = c.CEDULA 
    JOIN USUARIOS u ON rt.CEDULA_USUARIO = u.CEDULA;


/* Triggers */
CREATE OR REPLACE TRIGGER TRG_INSERTAR_ROL
AFTER INSERT ON AREAS
FOR EACH ROW
BEGIN
  INSERT INTO ROLES (NOMBRE_ROL) VALUES (:NEW.NOMBRE_AREA);
END;
/


/*INSERTS*/
INSERT INTO CLIENTES (CEDULA, NOMBRE, APELLIDO_1, APELLIDO_2, TIPO, FECHA_NAC, GENERO) VALUES ('111111111', 'Jared', 'Aguilar', 'MuÃ±oz', 'Afiliado', '29/10/2001', 'M');
INSERT INTO CLIENTES (CEDULA, NOMBRE, APELLIDO_1, APELLIDO_2, TIPO, FECHA_NAC, GENERO) VALUES ('222222222', 'Eduardo', 'Orellana', 'Rivas', 'Beneficiario', '19/06/2000', 'M');
INSERT INTO CLIENTES (CEDULA, NOMBRE, APELLIDO_1, APELLIDO_2, TIPO, FECHA_NAC, GENERO) VALUES ('333333333', 'Karen', 'Villalobos', 'Garita', 'Proveedor', '03/01/1990', 'F');
INSERT INTO CLIENTES (CEDULA, NOMBRE, APELLIDO_1, APELLIDO_2, TIPO, FECHA_NAC, GENERO) VALUES ('444444444', 'Mariela', 'RodrÃ­guez', 'Guevara', 'Jubilado', '22/12/1965', 'M');
INSERT INTO CLIENTES (CEDULA, NOMBRE, APELLIDO_1, APELLIDO_2, TIPO, FECHA_NAC, GENERO) VALUES ('555555555', 'Michelle', 'RodrÃ­guez', 'MuÃ±oz', 'Afiliado', '04/05/1998', 'F');

INSERT INTO AREAS (NOMBRE_AREA,DESCRIPCION_AREA, FECHA) VALUES ('ADMINISTRADOR','Realiza labores de mantenimiento', SYSDATE);
INSERT INTO AREAS (NOMBRE_AREA,DESCRIPCION_AREA, FECHA) VALUES ('VIGILANTE','Registros de entrada', SYSDATE);
INSERT INTO AREAS (NOMBRE_AREA, DESCRIPCION_AREA, FECHA) VALUES ('PRODUCTOSYSERVICIOS','Facilita diversos servicios y productos', SYSDATE);
INSERT INTO AREAS (NOMBRE_AREA, DESCRIPCION_AREA, FECHA) VALUES ('RECEPCION','Se atienden clientes', SYSDATE);

INSERT INTO ROLES (NOMBRE_ROL) VALUES ('ADMINISTRADOR');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('VIGILANTE');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('RECEPCION');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('PRODUCTOSYSERVICIOS');

INSERT INTO USUARIOS_ROLES VALUES ('ADMINISTRADOR', '402530551');
INSERT INTO USUARIOS_ROLES VALUES ('RECEPCION', '402530551');
INSERT INTO USUARIOS_ROLES VALUES ('VIGILANTE', '402530551');
INSERT INTO USUARIOS_ROLES VALUES ('PRODUCTOSYSERVICIOS', '402530551');

COMMIT;


INSERT INTO USUARIOS_ROLES VALUES ('PRODUCTOSYSERVICIOS', '208130058');
INSERT INTO USUARIOS_ROLES VALUES ('VIGILANTE', '208130058');


/*SELECTS*/
SELECT 
    ID_REGISTRO_ENTRADA, 
    CEDULA_CLIENTE, 
    ID_AREA_DESTINO, 
    MOTIVO_VISITA,
    FECHA_Y_HORA AS "FECHA", 
    TO_CHAR(FECHA_Y_HORA, 'HH:MI:SS') AS "HORA" 
FROM REGISTRO_ENTRADA;

--SELECT COUNT(*) FROM USUARIOS WHERE NOMBRE = 'Jared' AND CEDULA = '402530551';

--SELECT  TO_CHAR(FECHA, 'DD/MM/YYYY HH:MI:SS AM') AS FECHA_Y_HORA FROM AREAS;

--SELECT NOMBRE_ROL FROM USUARIOS_ROLES WHERE CEDULA_USUARIO = '402530551';

SELECT * FROM AREAS;
SELECT * FROM CLIENTES;
SELECT * FROM CLIENTES_INVITADOS;
SELECT * FROM REGISTRO_ENTRADA;
SELECT * FROM REGISTRO_TRAMITE;
SELECT * FROM ROLES;
SELECT * FROM TRAMITES;
SELECT * FROM TRAMITES_AREAS;
SELECT * FROM USUARIOS;
SELECT * FROM USUARIOS_ROLES;
SELECT * FROM REPORTE_COMPLETO;







SELECT T.ID_TRAMITE, T.NOMBRE_TRAMITE FROM TRAMITES T INNER JOIN TRAMITES_AREAS TA ON T.ID_TRAMITE = TA.ID_TRAMITE WHERE TA.ID_AREA = 261 AND T.ESTADO = 1;

SELECT 
ID_REGISTRO_ENTRADA,
CEDULA_CLIENTE,
A.NOMBRE_AREA,
MOTIVO_VISITA,
FECHA_Y_HORA
FROM REGISTRO_ENTRADA RE, AREAS A
WHERE A.ID_AREA = RE.ID_AREA_DESTINO;


 SELECT u.*, r.NOMBRE_ROL
      FROM USUARIOS u
      LEFT JOIN USUARIOS_ROLES ur ON u.CEDULA = ur.CEDULA_USUARIO
      LEFT JOIN SCTUNA.ROLES r ON ur.ID_ROL = r.ID_ROL
      WHERE u.CEDULA = '402450246';

SELECT * FROM AREAS;
SELECT * FROM TRAMITES WHERE ESTADO = 1;
SELECT * FROM INFORMACION_CLIENTES;
--SELECT * FROM ASOCIACION_AREA_TRAMITES;
--SELECT * FROM USERS;

/*RESTORE*/
DELETE FROM AREAS;
DELETE FROM CLIENTES;
DELETE FROM CLIENTES_INVITADOS;
DELETE FROM REGISTRO_ENTRADA;
DELETE FROM REGISTRO_TRAMITE;
DELETE FROM ROLES;
DELETE FROM TRAMITES;
DELETE FROM TRAMITES_AREAS;
DELETE FROM USUARIOS;
DELETE FROM USUARIOS_ROLES;

COMMIT;

/*DROP*/
DROP TABLE AREAS;
DROP TABLE CLIENTES;
DROP TABLE CLIENTES_INVITADOS;
DROP TABLE REGISTRO_ENTRADA;
DROP TABLE REGISTRO_TRAMITE;
DROP TABLE SCTUNA.ROLES;
DROP TABLE TRAMITES;
DROP TABLE TRAMITES_AREAS;
DROP TABLE USUARIOS;
DROP TABLE USUARIOS_ROLES;


DROP VIEW INFORMACION_CLIENTES;
DROP VIEW AREAS_POR_USUARIO;
DROP VIEW REPORTE_COMPLETO;

DROP SEQUENCE IDX_AREA_SEQ;
DROP SEQUENCE IDX_ROL_SEQ;
DROP SEQUENCE IDX_TRAMITE_SEQ;
DROP SEQUENCE IDX_REGISTRO_ENTRADA_SEQ;
DROP SEQUENCE IDX_REGISTRO_TRAMITE_SEQ;



/*TEST*/



COMMIT;
